# Generated by flox-agent import — do not edit by hand.
# source: https://github.com/flox/flox-skills @ 6a50cff2b9b77506106f3543342e43258f2c3ab1
{ buildAgentPlugin, fetchFromGitHub }:

buildAgentPlugin {
  name = "flox";
  version = "1.1.0";
  src = fetchFromGitHub {
    owner = "flox";
    repo = "flox-skills";
    rev = "6a50cff2b9b77506106f3543342e43258f2c3ab1";
    hash = "sha256-a6F+vYWP7izbla/IGkbrm4dc152MSnwJF23Baj6W69w=";
  };
  sourceUrl = "https://github.com/flox/flox-skills";

  manifest = {
    "$schema" = "https://agent-plugins.org/schemas/1.1.0/plugin.schema.json";
    author = {
      name = "Flox";
    };
    description = "Flox development environment and deployment plugin. Includes expert guidance for package management, services, builds and package distribution, containerization, environment composition and layering, and CI integration.";
    name = "flox";
    version = "1.1.0";
  };

  skills = {
    "flox" = "flox-plugin/skills/flox";
    "flox-debug" = "flox-plugin/skills/flox-debug";
    "floxify" = "flox-plugin/skills/floxify";
  };

  meta = {
    description = "Flox development environment and deployment plugin";
    homepage = "https://github.com/flox/flox-skills";
  };
}
